### ISSUE TITLE
Properties aren't being lifted for schemas

### ISSUE THREAD

**Issue by erikthered** [tobilg/api2html#6]
Let's say that I have a schema defined in my OpenAPI spec:

```yaml
  user:
    properties:
      id:
        type: string
        format: uuid
      login:
        type: string
        format: email
      password:
        type: string
        format: password
```

I would expect in the generated HTML to include only the properties, so basically this:
```javascript
{
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "login": {
      "type": "string",
      "format": "email"
    },
    "password": {
      "type": "string",
      "format": "password"
    },
}
```

However, it is rendering with the higher level fields:
```javascript
{
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "login": {
      "type": "string",
      "format": "email"
    },
    "password": {
      "type": "string",
      "format": "password"
    }
  }
}
```
You can also see this happening the example you link to in the README: https://tobilg.github.io/api2html/petstore/#schemas
